
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Setup GitHub Pages files
        run: |
          # Create .nojekyll file to disable Jekyll processing
          touch dist/.nojekyll
          # Create 404.html for SPA routing
          cp dist/index.html dist/404.html
          # Create a custom _headers file to set proper MIME types
          echo "/*" > dist/_headers
          echo "  Content-Type: text/html; charset=utf-8" >> dist/_headers
          echo "/assets/*" >> dist/_headers
          echo "  Content-Type: application/javascript; charset=utf-8" >> dist/_headers
