
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          
      - name: Debug build output
        run: |
          echo "Listing dist directory contents:"
          ls -la dist/
          echo "Checking for index.html:"
          cat dist/index.html | head -20
          echo "Checking asset paths:"
          grep -r "src=" dist/index.html || echo "No src attributes found"
          grep -r "href=" dist/index.html || echo "No href attributes found"

      - name: Setup GitHub Pages files
        run: |
          # Create .nojekyll file to disable Jekyll processing
          touch dist/.nojekyll
          
          # Create 404.html for SPA routing
          cp dist/index.html dist/404.html
          
          # Create timestamp file to verify deployment
          echo "Deployed on: $(date -u)" > dist/deploy-timestamp.txt
          
          # Create cache busting meta tag
          DEPLOY_ID=$(date +%s)
          echo "DEPLOY_ID=$DEPLOY_ID" >> $GITHUB_ENV
          
          # Create a test HTML file to confirm deployment
          cat > dist/deployment-status.html <<EOL
          <!DOCTYPE html>
          <html>
          <head>
            <title>DinoTradez Deployment Status</title>
            <meta name="deployment-id" content="$DEPLOY_ID">
            <style>
              body {
                background-color: #000000;
                color: #ffffff;
                font-family: 'Inter', sans-serif;
                margin: 0;
                padding: 20px;
                text-align: center;
              }
              .status {
                background-color: #0f172a;
                border-radius: 8px;
                padding: 20px;
                margin: 20px auto;
                max-width: 600px;
              }
              .timestamp {
                color: #3b82f6;
                font-weight: bold;
              }
            </style>
          </head>
          <body>
            <h1>🦖 DinoTradez Deployment Status</h1>
            <div class="status">
              <h2>Deployment Active</h2>
              <p>This page confirms that your deployment is active.</p>
              <p>Deployment ID: <span class="timestamp">$DEPLOY_ID</span></p>
              <p>Timestamp: <span class="timestamp">$(date -u)</span></p>
              <p><a href="./" style="color: #3b82f6;">Return to DinoTradez App</a></p>
            </div>
          </body>
          </html>
          EOL
          
          echo "Created deployment status page with ID: $DEPLOY_ID"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true

      - name: Deployment Summary
        run: |
          echo "## 🦖 DinoTradez Deployment" >> $GITHUB_STEP_SUMMARY
          echo "Deployment completed successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Deployment Details" >> $GITHUB_STEP_SUMMARY
          echo "- **Deployment ID:** ${DEPLOY_ID}" >> $GITHUB_STEP_SUMMARY
          echo "- **Timestamp:** $(date -u)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Important Notes" >> $GITHUB_STEP_SUMMARY
          echo "- GitHub Pages may take a few minutes to reflect changes" >> $GITHUB_STEP_SUMMARY
          echo "- Visit https://jjsppl.github.io/dinotradez/ to view your site" >> $GITHUB_STEP_SUMMARY
          echo "- Verify deployment at https://jjsppl.github.io/dinotradez/deployment-status.html" >> $GITHUB_STEP_SUMMARY
